### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by AntonioAbilio** [AntonioAbilio/LCOM_Minix_AppleSilicon_Tutorial#1]
Add to tutorial: 
- [x] Maybe some photos.
- [x] How to configure the serial ports.
- [x] Important information on what not to do.
